#!/bin/sh
#
#####################################################################
##
##       DWS4000 LCD_Mon for CFA LCD and Backfire 10.3 @linux2.6
##
##            Copyright 2018, by Dasan InfoTek Co.,
##
##                      ...jsLee, leesy...
##
#####################################################################

pSleep() {
	cntP1=`expr $1 \* 1`
	# Infinite while loop
	while :
	do
		if [ $cntP1 -gt 0 ] ; then
			fping -q 127.0.0.1
		else
			break
		fi
		cntP1=`expr $cntP1 - 1`
	done
}

readCFG() {
	cWssid=`uci -q get wireless.@wifi-iface[0].ssid`
	cWencr=`uci -q get wireless.@wifi-iface[0].encryption`
	cWkey=`uci -q get wireless.@wifi-iface[0].key`

	cWip=`uci -q get network.wlan.ipaddr`
	cWmask=`uci -q get network.wlan.netmask`
	cWgway=`uci -q get network.wlan.gateway`
	cWdns=`uci -q get network.wlan.dns`

	# cLip=`uci show network.lan.ipaddr | cut -d'=' -f2`
	# cLmask=`uci show network.lan.netmask | cut -d'=' -f2`

	# cSlogip=`uci show system.@system[0].log_ip | cut -d'=' -f2`

	## echo "wSSID=$cWssid $cWencr Key=$cWkey $cWip $cWmask $cWgway $cLip $cLmask $cSlogip $cWdns "

	##rSNR=`iwconfig ath0 | grep Link | awk '{print $2}' | cut -d'=' -f2 | cut -d'/' -f1`
	##rFreq=`iwconfig ath0 | grep  Freq  | awk '{ print $2 }' | cut -c11-`
	##rAP=`iwconfig ath0 | grep Freq | awk '{ print $6 }'`

	iwconfig ath0 > /tmp/ath0s
	##
	rSNR=`cat /tmp/ath0s | grep Link | awk '{print $2}' | cut -d'=' -f2 | cut -d'/' -f1`
	rFreq=`cat /tmp/ath0s | grep  Freq  | awk '{ print $2 }' | cut -c11-`
	rAP=`cat /tmp/ath0s | grep Freq | awk '{ print $6 }'`
	##
	rSSID=`cat /tmp/ath0s | grep SSID | awk '{print $3" "$4}'`

	upTime=`uptime | cut -d',' -f1 | sed 's/^ *//g'`
	upTime=`echo "$upTime        " | cut -c -20`

	rDATE=`date +%Y%m%e`
	rDATE="$rDATE $upTime"
	rDATE=`echo "$rDATE" | sed 's/^ *//g' | cut -c -20`
}

###### Start of main script

### Check and wait USB serial character device file exists
USB_SERIAL_DEV_EXIST=0
while [ ! -c /dev/ttyUSB0 ]
do
	sleep 1 # wait 1sec
	echo Check USB serial device exist!
done
USB_SERIAL_DEV_EXIST=1
sleep 1 # wait 1sec

### Check CFA LCD
## Ping LCD
cfa_send /dev/ttyUSB0 "\x00\d000"
if [ $? -eq 0 ] ; then
	CFA_DETECTED=1
else
	CFA_DETECTED=0
fi
# echo "CFA_DETECTED=$CFA_DETECTED" 

# Init LCD
if [ $CFA_DETECTED -eq 1 ] ; then
	### Init CFA LCD
	## Set keypad backlight off
	cfa_send /dev/ttyUSB0 "\x0e\d002\d100\d000"
	## Display splash strings
	cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d000DASAN InfoTek       "
	cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d001                    "
	cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d002                    "
	cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d003   www.dsintek.co.kr"
	## Store current state as boot state
	cfa_send /dev/ttyUSB0 "\x04\d000"
else
	stty -F /dev/ttyUSB0 115200
	sleep 1 # wait 1sec
	##
	echo -n -e '\x1B\x43' > /dev/ttyUSB0
	sleep 1 # wait 1sec
fi

# infinite while loop 
while :
do
	pSleep 9 #9msec

	readCFG

	rAP=`echo $rAP | cut -c 12- `    ## ":C6:C4"  ## Not-Associated : "ciated"
	###
	if [ "$rAP" == "ted" ] ; then
		rAP="Not-AP"
		rSNR=0
	fi
	
	if [ $CFA_DETECTED -eq 1 ] ; then
		cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d000IP:$cWip                    "   ### Locate 0,0
		
		cfa_send /dev/ttyUSB0 "\x1f\d016\d000\d001ID:$cWssid              "   ### Locate 0,1
		
		cfa_send /dev/ttyUSB0 "\x1f\d008\d014\d001$rAP      "   ### Locate 14,1
		
		cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d002FQ:$rFreq SNR:$rSNR                    "   ### Locate 0,2
		
		cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d003$upTime                    "   ### Locate 0,3
	else
		echo -n -e '\x1B\x4C\x00\x00' > /dev/ttyUSB0   ### Locate 0,0
		echo -n "IP:$cWip" > /dev/ttyUSB0
		
		echo -n -e '\x1B\x4C\x00\x01' > /dev/ttyUSB0   ### Locate 0,1
		echo -n "ID:$cWssid " > /dev/ttyUSB0
		
		echo -n -e '\x1B\x4C\x0E\x01' > /dev/ttyUSB0   ### Locate 14,1
		echo -n "$rAP" > /dev/ttyUSB0
		
		echo -n -e '\x1B\x4C\x00\x02' > /dev/ttyUSB0   ### Locate 0,2
		echo -n "FQ:$rFreq SNR:$rSNR " > /dev/ttyUSB0
		
		echo -n -e '\x1B\x4C\x00\x03' > /dev/ttyUSB0   ### Locate 0,3
		echo -n "$upTime" > /dev/ttyUSB0
	fi

	### Check and wait USB serial character device file exists
	while [ ! -c /dev/ttyUSB0 ]
	do
		USB_SERIAL_DEV_EXIST=0
		sleep 1 # wait 1sec
		echo Check USB serial device exist!
	done

	if [ $USB_SERIAL_DEV_EXIST -eq 0 ] ; then
		sleep 1 # wait 1sec
		USB_SERIAL_DEV_EXIST=1
		### Check CFA LCD
		## Ping LCD
		cfa_send /dev/ttyUSB0 "\x00\d000"
		if [ $? -eq 0 ] ; then
			CFA_DETECTED=1
		else
			CFA_DETECTED=0
		fi
		# echo "CFA_DETECTED=$CFA_DETECTED" 

		# Init LCS
		if [ $CFA_DETECTED -eq 1 ] ; then
			### Init CFA LCD
			## Set keypad backlight off
			cfa_send /dev/ttyUSB0 "\x0e\d002\d100\d000"
			## Display splash strings
			cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d000DASAN InfoTek       "
			cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d001                    "
			cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d002                    "
			cfa_send /dev/ttyUSB0 "\x1f\d022\d000\d003   www.dsintek.co.kr"
			## Store current state as boot state
			cfa_send /dev/ttyUSB0 "\x04\d000"
		else
			stty -F /dev/ttyUSB0 115200
			sleep 1
			##
			echo -n -e '\x1B\x43' > /dev/ttyUSB0
			sleep 1
		fi
	fi
done
##### END of Main script ###
